#!/usr/bin/lua

local f = io.open('/usr/lib/micron.d/checkgw', 'w')
f:write(string.format('0,30 * * * * sleep 6; /lib/gluon/ffws-chkgw/gw_test.sh\n'))
f:write(string.format('3 3 * * * /usr/sbin/ntpd -n -p svc.services.ffws\n'))
f:write(string.format('4 3 * * * killall ntpd\n'))
f:close()
